#!/bin/sh

if [ -z "$IDF_PATH" ]; then
	echo "set IDF_PATH environment variable to root of the IDF directory"
	exit 1
fi

case "$IDF_BSP" in
	"wemos-lolin-s3-mini")
	;;
	"lilygo-t7-s3")
	;;
	*)
		echo "set IDF_BSP environment variable to the name of the board:"
		echo "- wemos-lolin-s3-mini"
		echo "- lilygo-t7-s3"
		exit 1
	;;
esac

export IDF_BUILD="${PWD}/board/${IDF_BSP}/build"
export IDF_DEFAULTS="SDKCONFIG_DEFAULTS=${PWD}/sdkconfig.defaults;${PWD}/board/${IDF_BSP}/sdkconfig.defaults"

source $IDF_PATH/export.sh > /dev/null

set -x

exec idf.py -B "${IDF_BUILD}" -D "${IDF_DEFAULTS}" -p /dev/ttyACM0 -b 1000000 "$@"
