#!/bin/zsh

if [ -z "$IDF_PATH" ]; then
	echo "set IDF_PATH environment variable to root of the IDF directory"
	exit 1
fi

case "$IDF_BSP" in
	"wemos-lolin-s3-mini")
	;;
	"lilygo-t7-s3")
	;;
	"espressif-s3-box3")
	;;
	*)
		echo "set IDF_BSP environment variable to the name of the board:"
		echo "- wemos-lolin-s3-mini"
		echo "- lilygo-t7-s3"
		echo "- espressif-s3-box3"
		exit 1
	;;
esac

export IDF_BUILD="${PWD}/board/${IDF_BSP}/build"
export IDF_DEFAULTS="SDKCONFIG_DEFAULTS=${PWD}/sdkconfig.defaults;${PWD}/board/${IDF_BSP}/sdkconfig.defaults"

a=$(export)

if [ ! -f environment ]; then
	echo "*** No environment cache, running idf update"
	touch environment
	idf update
fi

while read line; do
	export $line
done < environment

case "$1" in
	build)
		cd "$IDF_BUILD"
		shift

		args=()

		for arg in "$@"; do
			obj="${arg/.o/.cpp.obj}"
			obj="${obj/.cpp/.cpp.obj}"
			args+="esp-idf/main/CMakeFiles/__idf_main.dir/${obj}"
		done

		exec ninja ${args[*]}
		;;

	monitor)
		cd "$IDF_BUILD"
		shift
		exec ninja "$@"
		;;

	run)
		exec idf.py -B "${IDF_BUILD}" -D "${IDF_DEFAULTS}" -p /dev/ttyACM0 app-flash monitor
		;;

	update)
		rm -f /tmp/a /tmp/b
		LOCALE="C" echo "$a" | sort -u > /tmp/a
		zsh -c ". $IDF_PATH/export.sh; LOCALE="C"; export | sort -u > /tmp/b"
		comm -3 /tmp/a /tmp/b | sed -e 's/^	//' -e '/SHLVL=/d' > environment
		rm -f /tmp/a /tmp/b
		;;

	*)
		exec idf.py -B "${IDF_BUILD}" -D "${IDF_DEFAULTS}" -p /dev/ttyACM0 "$@"
		;;
esac
